// <auto-generated />
namespace Pulse.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class lateststuff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lateststuff));
        
        string IMigrationMetadata.Id
        {
            get { return "201505280928292_latest-stuff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
